


INSERT INTO mundiales_stats (seleccion,titulos,finales,semifinales,cuartos,octavos,segundaronda,fasegrupos,mejorresultado) VALUES ('Brasil',5,7,8,14,12,3,20,'Campeón (1958, 1962, 1970, 1994, 2002)');
INSERT INTO mundiales_stats (seleccion,titulos,finales,semifinales,cuartos,octavos,segundaronda,fasegrupos,mejorresultado) VALUES ('Alemania',4,8,12,14,10,3,18,'Campeón (1954, 1974, 1990, 2014)');
INSERT INTO mundiales_stats (seleccion,titulos,finales,semifinales,cuartos,octavos,segundaronda,fasegrupos,mejorresultado) VALUES ('Italia',4,6,7,6,8,2,16,'Campeón (1934, 1938, 1982, 2006)');
INSERT INTO mundiales_stats (seleccion,titulos,finales,semifinales,cuartos,octavos,segundaronda,fasegrupos,mejorresultado) VALUES ('Argentina',3,6,5,8,10,3,17,'Campeón (1978, 1986, 2022)');
INSERT INTO mundiales_stats (seleccion,titulos,finales,semifinales,cuartos,octavos,segundaronda,fasegrupos,mejorresultado) VALUES ('Francia',2,4,7,8,8,1,14,'Campeón (1998, 2018)');
INSERT INTO mundiales_stats (seleccion,titulos,finales,semifinales,cuartos,octavos,segundaronda,fasegrupos,mejorresultado) VALUES ('Uruguay',2,2,4,5,5,null,14,'Campeón (1930, 1950)');
INSERT INTO mundiales_stats (seleccion,titulos,finales,semifinales,cuartos,octavos,segundaronda,fasegrupos,mejorresultado) VALUES ('Inglaterra',1,1,3,10,8,1,16,'Campeón (1966)');
INSERT INTO mundiales_stats (seleccion,titulos,finales,semifinales,cuartos,octavos,segundaronda,fasegrupos,mejorresultado) VALUES ('España',1,1,1,5,9,1,15,'Campeón (2010)');
INSERT INTO mundiales_stats (seleccion,titulos,finales,semifinales,cuartos,octavos,segundaronda,fasegrupos,mejorresultado) VALUES ('Países Bajos',null,3,3,5,9,2,9,'Finalista (1974, 1978, 2010)');
INSERT INTO mundiales_stats (seleccion,titulos,finales,semifinales,cuartos,octavos,segundaronda,fasegrupos,mejorresultado) VALUES ('Hungría',null,2,2,5,2,null,7,'Finalista (1938, 1954)');
INSERT INTO mundiales_stats (seleccion,titulos,finales,semifinales,cuartos,octavos,segundaronda,fasegrupos,mejorresultado) VALUES ('República Checa',null,2,2,4,3,null,7,'Finalista (1934, 1962)');
INSERT INTO mundiales_stats (seleccion,titulos,finales,semifinales,cuartos,octavos,segundaronda,fasegrupos,mejorresultado) VALUES ('Suecia',null,1,3,5,6,1,10,'Finalista (1958)');
INSERT INTO mundiales_stats (seleccion,titulos,finales,semifinales,cuartos,octavos,segundaronda,fasegrupos,mejorresultado) VALUES ('Croacia',null,1,3,3,3,null,6,'Finalista (2018)');
INSERT INTO mundiales_stats (seleccion,titulos,finales,semifinales,cuartos,octavos,segundaronda,fasegrupos,mejorresultado) VALUES ('Serbia',null,null,2,4,2,1,13,'Semifinales (1930, 1962)');
INSERT INTO mundiales_stats (seleccion,titulos,finales,semifinales,cuartos,octavos,segundaronda,fasegrupos,mejorresultado) VALUES ('Bélgica',null,null,2,3,8,1,12,'Semifinales (1986, 2018)');
INSERT INTO mundiales_stats (seleccion,titulos,finales,semifinales,cuartos,octavos,segundaronda,fasegrupos,mejorresultado) VALUES ('Portugal',null,null,2,3,4,null,8,'Semifinales (1966, 2006)');
INSERT INTO mundiales_stats (seleccion,titulos,finales,semifinales,cuartos,octavos,segundaronda,fasegrupos,mejorresultado) VALUES ('Austria',null,null,2,2,1,2,6,'Semifinales (1934, 1954)');
INSERT INTO mundiales_stats (seleccion,titulos,finales,semifinales,cuartos,octavos,segundaronda,fasegrupos,mejorresultado) VALUES ('Rusia',null,null,1,5,2,1,11,'Semifinales (1966)');
INSERT INTO mundiales_stats (seleccion,titulos,finales,semifinales,cuartos,octavos,segundaronda,fasegrupos,mejorresultado) VALUES ('Estados Unidos',null,null,1,1,6,null,10,'Semifinales (1930)');
INSERT INTO mundiales_stats (seleccion,titulos,finales,semifinales,cuartos,octavos,segundaronda,fasegrupos,mejorresultado) VALUES ('Chile',null,null,1,1,3,null,9,'Semifinales (1962)');
INSERT INTO mundiales_stats (seleccion,titulos,finales,semifinales,cuartos,octavos,segundaronda,fasegrupos,mejorresultado) VALUES ('Corea del Sur',null,null,1,1,3,null,11,'Semifinales (2002)');
INSERT INTO mundiales_stats (seleccion,titulos,finales,semifinales,cuartos,octavos,segundaronda,fasegrupos,mejorresultado) VALUES ('Bulgaria',null,null,1,1,2,null,7,'Semifinales (1994)');
INSERT INTO mundiales_stats (seleccion,titulos,finales,semifinales,cuartos,octavos,segundaronda,fasegrupos,mejorresultado) VALUES ('Marruecos',null,null,1,1,2,null,6,'Semifinales (2022)');
INSERT INTO mundiales_stats (seleccion,titulos,finales,semifinales,cuartos,octavos,segundaronda,fasegrupos,mejorresultado) VALUES ('Turquía',null,null,1,1,1,null,2,'Semifinales (2002)');
INSERT INTO mundiales_stats (seleccion,titulos,finales,semifinales,cuartos,octavos,segundaronda,fasegrupos,mejorresultado) VALUES ('Polonia',null,null,1,null,3,3,8,'Semifinales (1982)');
INSERT INTO mundiales_stats (seleccion,titulos,finales,semifinales,cuartos,octavos,segundaronda,fasegrupos,mejorresultado) VALUES ('Suiza',null,null,null,3,7,null,10,'Cuartos de final (1934, 1938, 1954)');
INSERT INTO mundiales_stats (seleccion,titulos,finales,semifinales,cuartos,octavos,segundaronda,fasegrupos,mejorresultado) VALUES ('México',null,null,null,2,8,null,17,'Cuartos de final (1970, 1986)');
INSERT INTO mundiales_stats (seleccion,titulos,finales,semifinales,cuartos,octavos,segundaronda,fasegrupos,mejorresultado) VALUES ('Paraguay',null,null,null,1,4,null,8,'Cuartos de final (2010)');
INSERT INTO mundiales_stats (seleccion,titulos,finales,semifinales,cuartos,octavos,segundaronda,fasegrupos,mejorresultado) VALUES ('Dinamarca',null,null,null,1,4,null,6,'Cuartos de final (1998)');
INSERT INTO mundiales_stats (seleccion,titulos,finales,semifinales,cuartos,octavos,segundaronda,fasegrupos,mejorresultado) VALUES ('Rumania',null,null,null,1,5,null,5,'Cuartos de final (1994)');
INSERT INTO mundiales_stats (seleccion,titulos,finales,semifinales,cuartos,octavos,segundaronda,fasegrupos,mejorresultado) VALUES ('Colombia',null,null,null,1,3,null,6,'Cuartos de final (2014)');
INSERT INTO mundiales_stats (seleccion,titulos,finales,semifinales,cuartos,octavos,segundaronda,fasegrupos,mejorresultado) VALUES ('Irlanda',null,null,null,1,3,null,3,'Cuartos de final (1990)');
INSERT INTO mundiales_stats (seleccion,titulos,finales,semifinales,cuartos,octavos,segundaronda,fasegrupos,mejorresultado) VALUES ('Costa Rica',null,null,null,1,2,null,6,'Cuartos de final (2014)');
INSERT INTO mundiales_stats (seleccion,titulos,finales,semifinales,cuartos,octavos,segundaronda,fasegrupos,mejorresultado) VALUES ('Ghana',null,null,null,1,2,null,4,'Cuartos de final (2010)');
INSERT INTO mundiales_stats (seleccion,titulos,finales,semifinales,cuartos,octavos,segundaronda,fasegrupos,mejorresultado) VALUES ('Senegal',null,null,null,1,2,null,3,'Cuartos de final (2002)');
INSERT INTO mundiales_stats (seleccion,titulos,finales,semifinales,cuartos,octavos,segundaronda,fasegrupos,mejorresultado) VALUES ('Perú',null,null,null,1,null,1,5,'Cuartos de final (1970)');
INSERT INTO mundiales_stats (seleccion,titulos,finales,semifinales,cuartos,octavos,segundaronda,fasegrupos,mejorresultado) VALUES ('Irlanda del Norte',null,null,null,1,null,1,3,'Cuartos de final (1958)');
INSERT INTO mundiales_stats (seleccion,titulos,finales,semifinales,cuartos,octavos,segundaronda,fasegrupos,mejorresultado) VALUES ('Camerún',null,null,null,1,1,null,8,'Cuartos de final (1990)');
INSERT INTO mundiales_stats (seleccion,titulos,finales,semifinales,cuartos,octavos,segundaronda,fasegrupos,mejorresultado) VALUES ('Corea del Norte',null,null,null,1,null,null,2,'Cuartos de final (1966)');
INSERT INTO mundiales_stats (seleccion,titulos,finales,semifinales,cuartos,octavos,segundaronda,fasegrupos,mejorresultado) VALUES ('Gales',null,null,null,1,null,null,2,'Cuartos de final (1958)');
INSERT INTO mundiales_stats (seleccion,titulos,finales,semifinales,cuartos,octavos,segundaronda,fasegrupos,mejorresultado) VALUES ('Cuba',null,null,null,1,1,null,null,'Cuartos de final (1938)');
INSERT INTO mundiales_stats (seleccion,titulos,finales,semifinales,cuartos,octavos,segundaronda,fasegrupos,mejorresultado) VALUES ('Ucrania',null,null,null,1,1,null,1,'Cuartos de final (2006)');
INSERT INTO mundiales_stats (seleccion,titulos,finales,semifinales,cuartos,octavos,segundaronda,fasegrupos,mejorresultado) VALUES ('Alemania Dem.',null,null,null,null,null,1,1,'Segunda ronda (1974)');
INSERT INTO mundiales_stats (seleccion,titulos,finales,semifinales,cuartos,octavos,segundaronda,fasegrupos,mejorresultado) VALUES ('Japón',null,null,null,null,4,null,7,'Octavos de final (2002, 2010, 2018, 2022)');
INSERT INTO mundiales_stats (seleccion,titulos,finales,semifinales,cuartos,octavos,segundaronda,fasegrupos,mejorresultado) VALUES ('Nigeria',null,null,null,null,3,null,6,'Octavos de final (1994, 1998, 2014)');
INSERT INTO mundiales_stats (seleccion,titulos,finales,semifinales,cuartos,octavos,segundaronda,fasegrupos,mejorresultado) VALUES ('Australia',null,null,null,null,2,null,6,'Octavos de final (2006, 2022)');
INSERT INTO mundiales_stats (seleccion,titulos,finales,semifinales,cuartos,octavos,segundaronda,fasegrupos,mejorresultado) VALUES ('Arabia Saudí',null,null,null,null,1,null,6,'Octavos de final (1994)');
INSERT INTO mundiales_stats (seleccion,titulos,finales,semifinales,cuartos,octavos,segundaronda,fasegrupos,mejorresultado) VALUES ('Argelia',null,null,null,null,1,null,4,'Octavos de final (2014)');
INSERT INTO mundiales_stats (seleccion,titulos,finales,semifinales,cuartos,octavos,segundaronda,fasegrupos,mejorresultado) VALUES ('Ecuador',null,null,null,null,1,null,4,'Octavos de final (2006)');
INSERT INTO mundiales_stats (seleccion,titulos,finales,semifinales,cuartos,octavos,segundaronda,fasegrupos,mejorresultado) VALUES ('Noruega',null,null,null,null,2,null,2,'Octavos de final (1998)');
INSERT INTO mundiales_stats (seleccion,titulos,finales,semifinales,cuartos,octavos,segundaronda,fasegrupos,mejorresultado) VALUES ('Grecia',null,null,null,null,1,null,3,'Octavos de final (2014)');
INSERT INTO mundiales_stats (seleccion,titulos,finales,semifinales,cuartos,octavos,segundaronda,fasegrupos,mejorresultado) VALUES ('Eslovaquia',null,null,null,null,1,null,1,'Octavos de final (2010)');
INSERT INTO mundiales_stats (seleccion,titulos,finales,semifinales,cuartos,octavos,segundaronda,fasegrupos,mejorresultado) VALUES ('Indonesia',null,null,null,null,1,null,null,'Octavos de final (1938)');
INSERT INTO mundiales_stats (seleccion,titulos,finales,semifinales,cuartos,octavos,segundaronda,fasegrupos,mejorresultado) VALUES ('Egipto',null,null,null,null,1,null,2,'Octavos de final (1934)');
INSERT INTO mundiales_stats (seleccion,titulos,finales,semifinales,cuartos,octavos,segundaronda,fasegrupos,mejorresultado) VALUES ('Escocia',null,null,null,null,null,null,8,'1.ª ronda (1954, 1958, 1974, 1978, 1982, 1986, 1990, 1998)');
INSERT INTO mundiales_stats (seleccion,titulos,finales,semifinales,cuartos,octavos,segundaronda,fasegrupos,mejorresultado) VALUES ('Túnez',null,null,null,null,null,null,6,'1.ª ronda (1978, 1998, 2002, 2006, 2018, 2022)');
INSERT INTO mundiales_stats (seleccion,titulos,finales,semifinales,cuartos,octavos,segundaronda,fasegrupos,mejorresultado) VALUES ('Irán',null,null,null,null,null,null,6,'1.ª ronda (1978, 1998, 2006, 2014, 2018, 2022)');
INSERT INTO mundiales_stats (seleccion,titulos,finales,semifinales,cuartos,octavos,segundaronda,fasegrupos,mejorresultado) VALUES ('Bolivia',null,null,null,null,null,null,3,'1.ª ronda (1930, 1950, 1994)');
INSERT INTO mundiales_stats (seleccion,titulos,finales,semifinales,cuartos,octavos,segundaronda,fasegrupos,mejorresultado) VALUES ('Honduras',null,null,null,null,null,null,3,'1.ª ronda (1982, 2010, 2014)');
INSERT INTO mundiales_stats (seleccion,titulos,finales,semifinales,cuartos,octavos,segundaronda,fasegrupos,mejorresultado) VALUES ('Sudáfrica',null,null,null,null,null,null,3,'1.ª ronda (1998, 2002, 2010)');
INSERT INTO mundiales_stats (seleccion,titulos,finales,semifinales,cuartos,octavos,segundaronda,fasegrupos,mejorresultado) VALUES ('Costa de Marfil',null,null,null,null,null,null,3,'1.ª ronda (2006, 2010, 2014)');
INSERT INTO mundiales_stats (seleccion,titulos,finales,semifinales,cuartos,octavos,segundaronda,fasegrupos,mejorresultado) VALUES ('El Salvador',null,null,null,null,null,null,2,'1.ª ronda (1970, 1982)');
INSERT INTO mundiales_stats (seleccion,titulos,finales,semifinales,cuartos,octavos,segundaronda,fasegrupos,mejorresultado) VALUES ('Nueva Zelanda',null,null,null,null,null,null,2,'1.ª ronda (1982, 2010)');
INSERT INTO mundiales_stats (seleccion,titulos,finales,semifinales,cuartos,octavos,segundaronda,fasegrupos,mejorresultado) VALUES ('Eslovenia',null,null,null,null,null,null,2,'1.ª ronda (2002, 2010)');
INSERT INTO mundiales_stats (seleccion,titulos,finales,semifinales,cuartos,octavos,segundaronda,fasegrupos,mejorresultado) VALUES ('Canadá',null,null,null,null,null,null,2,'1.ª ronda (1986, 2022)');
INSERT INTO mundiales_stats (seleccion,titulos,finales,semifinales,cuartos,octavos,segundaronda,fasegrupos,mejorresultado) VALUES ('Israel',null,null,null,null,null,null,1,'1.ª ronda (1970)');
INSERT INTO mundiales_stats (seleccion,titulos,finales,semifinales,cuartos,octavos,segundaronda,fasegrupos,mejorresultado) VALUES ('Haití',null,null,null,null,null,null,1,'1.ª ronda (1974)');
INSERT INTO mundiales_stats (seleccion,titulos,finales,semifinales,cuartos,octavos,segundaronda,fasegrupos,mejorresultado) VALUES ('Rep. Dem. del Congo',null,null,null,null,null,null,1,'1.ª ronda (1974)');
INSERT INTO mundiales_stats (seleccion,titulos,finales,semifinales,cuartos,octavos,segundaronda,fasegrupos,mejorresultado) VALUES ('Kuwait',null,null,null,null,null,null,1,'1.ª ronda (1982)');
INSERT INTO mundiales_stats (seleccion,titulos,finales,semifinales,cuartos,octavos,segundaronda,fasegrupos,mejorresultado) VALUES ('Irak',null,null,null,null,null,null,1,'1.ª ronda (1986)');
INSERT INTO mundiales_stats (seleccion,titulos,finales,semifinales,cuartos,octavos,segundaronda,fasegrupos,mejorresultado) VALUES ('Emiratos Árabes Unidos',null,null,null,null,null,null,1,'1.ª ronda (1990)');
INSERT INTO mundiales_stats (seleccion,titulos,finales,semifinales,cuartos,octavos,segundaronda,fasegrupos,mejorresultado) VALUES ('Jamaica',null,null,null,null,null,null,1,'1.ª ronda (1998)');
INSERT INTO mundiales_stats (seleccion,titulos,finales,semifinales,cuartos,octavos,segundaronda,fasegrupos,mejorresultado) VALUES ('China',null,null,null,null,null,null,1,'1.ª ronda (2002)');
INSERT INTO mundiales_stats (seleccion,titulos,finales,semifinales,cuartos,octavos,segundaronda,fasegrupos,mejorresultado) VALUES ('Angola',null,null,null,null,null,null,1,'1.ª ronda (2006)');
INSERT INTO mundiales_stats (seleccion,titulos,finales,semifinales,cuartos,octavos,segundaronda,fasegrupos,mejorresultado) VALUES ('Togo',null,null,null,null,null,null,1,'1.ª ronda (2006)');
INSERT INTO mundiales_stats (seleccion,titulos,finales,semifinales,cuartos,octavos,segundaronda,fasegrupos,mejorresultado) VALUES ('Trinidad y Tobago',null,null,null,null,null,null,1,'1.ª ronda (2006)');
INSERT INTO mundiales_stats (seleccion,titulos,finales,semifinales,cuartos,octavos,segundaronda,fasegrupos,mejorresultado) VALUES ('Bosnia y Herzegovina',null,null,null,null,null,null,1,'1.ª ronda (2014)');
INSERT INTO mundiales_stats (seleccion,titulos,finales,semifinales,cuartos,octavos,segundaronda,fasegrupos,mejorresultado) VALUES ('Islandia',null,null,null,null,null,null,1,'1.ª ronda (2018)');
INSERT INTO mundiales_stats (seleccion,titulos,finales,semifinales,cuartos,octavos,segundaronda,fasegrupos,mejorresultado) VALUES ('Panamá',null,null,null,null,null,null,1,'1.ª ronda (2018)');
INSERT INTO mundiales_stats (seleccion,titulos,finales,semifinales,cuartos,octavos,segundaronda,fasegrupos,mejorresultado) VALUES ('Catar',null,null,null,null,null,null,1,'1.ª ronda (2022)');